project:
  type: website
  output-dir: docs

website:
  title: "Brandt Lab - AMP"
  navbar:
    floating: true
    right:
      - href: about.qmd
        text: About
      - href: visualizations.qmd
        text: Visualizations
      - href: publications.qmd
        text: Publications
      - href: site-maps.qmd
        text: Site Maps
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



