project:
  type: website
  output-dir: docs

website:
  title: "Acropora Monitoring Program"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Site Maps"
        href: site-maps.qmd
      - text: "Visualizations"
        href: visualizations.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Contact"
        href: contact.qmd
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



